services:
  bolt:
    image: bolt-ai:chh1107
    container_name: bolt
    build:
      context: .
      dockerfile: Dockerfile
    env_file: '.env'
    environment:
      - NODE_ENV=development
      - VITE_HMR_PROTOCOL=ws
      - VITE_HMR_HOST=${BOLT_HOST:-localhost}
      - VITE_HMR_PORT=5173
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - PORT=5173
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-debug}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      - RUNNING_IN_DOCKER=true
      - OPENAI_LIKE_API_BASE_URL=${OPENAI_LIKE_API_BASE_URL}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '5173:5173'
    networks:
      bolt:

networks:
  bolt:
    name: bolt
    driver: bridge
    # Adjust the MTU value according to your physical system setup. Default is 1500.
    # A wrong value will lead to weird connection issues (e.g., apt cannot retrieve packages and so on).
    # driver_opts:
    #   com.docker.network.driver.mtu: 1450